language: java
addons:
  sonarcloud:
    organization: "alfasoftware"
    token:
      secure: "c0ZrSWhXio4F0JeaKBvxeG/gJnjT3kssShmB3/Z1b7uupg/bG2tjQy/7OfYVxvd5UVrlPSNTs2/yjjqe6f8lCY5ts6rA1BjsY+w7GOS37GJb/uDLEybsnj8A57JVai7ALp0P5Vih3R0nPOuCzwK1TsduQvrtvIl3sOdevN640K3tRRhHjdfj4HfnM0fNOceuiWooTcaZLYrIxA2X8Zs4PAMO/aV6kOdQ7eIy2fZ5z86lZY5RIADgXgHR4tM2Hg4POZd9OhGu9wdhKkVwHKsFTggZvXT20QmOFjUcJEEgWNxARclCqFUgtjUl7N6niwe91jzkgNXtPThthXO98JX2VynigO6FmXXmxNuNDXIWSuSGB1PtFtNOglidlmM4W5gUNcU1FNT1TJSGO2V5t4Zl9N+URKW70iLXLsu5gVu9kL+OeKcOJqDs8nEeSMzA6pQvjvl/xP0iwQMT/7l6TyweJUmIBIXy6KQzaww95mPoptWVSJIuwU+/MtxBEpHT+UJI9T+TaBAEyvmGmF/YtJlMTpm2ffORjaHHCX/xcLM+lmSpZWD1rMb8xYtQhCQFqU8U5kH/3bD4Lly+iDxbPIRRLthzGGK1f4nXWkCpK+b+q2eU4VyYTAgd/xRVsRBrYSFYnEvHHfr7iy37q3jPlIF7MrQdqo2WIH+ii6tuduGLAO4="
jobs:
  include:
   - if: repo = alfasoftware/astra AND head_repo = alfasoftware/astra AND type = pull_request
     name: "Test"
     script:
        - git fetch --quiet
        - mvn clean verify sonar:sonar -Pcoverage -B -U -Dsonar.pullrequest.key=$TRAVIS_PULL_REQUEST -Dsonar.pullrequest.branch=$TRAVIS_PULL_REQUEST_BRANCH -Dsonar.pullrequest.base=$TRAVIS_BRANCH
   - if: repo = alfasoftware/astra AND (branch = main OR tag IS present) AND NOT type = pull_request
     name: "Deploy"
     script:
        - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
        - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
        - mvn clean deploy --settings .maven-settings.xml -B -U -Prelease
