language: java
install: true
addons:
  sonarcloud:
    organization: "alfasoftware"
    token:
      secure: "B5yJ3PKSz46CKdYNpZkZ2nwi2RYjnmaGgp2GNWmZgR/+EFgYI+paie7RQpsdZDNRW7M6wklZYP5ef45EIb20d4YIXP8ZLWGQuNUmQBh9rV+slobSbncCT0wMT/vQGaHBbrptYyy2DFj8jpuNPVsaeBnvs+ZsSXiz/pcFYBYtlLt4olxgKKKZtv/Q23/F2chc/VgMqaoLM1PbqBF/N5ct6LTszm55q22SFf+H3/kPVpgzcdXcun2LZ3LEY6HAJqZUEEW2YOfAMuezIGQAr4OeulXIsfloOiHNLShJSJs/CfDU08HCWjtFg6O8n4JuSFK3rf98jHo6FxHHpT6IoiEsbM6R1de9RhlQdgyugzueEdQl9K07INYg4QFW/1Lb/qsvlcW16NdGPFy4evE1bdCnLxb5l7wXBCNSJ4xjzx22hxxnj4P4JRvyyPeTlsedHovBNh0+3OsyfW1ol37xbEAez2hF0nM83Cqe5D1jLy0nfmn3aPukDFPY2Nz1+i+/rU4sKIK8H27rXikil7jBRzclJTxbK3gHVT6JTKy/97NgPZyEHjqgtJYV10szoeRFV8mQN4L6x7kwtBNazh38e4WBjZ/gzV+f7idv7v82PPppcrfNC/+7jM2xKp9dllZ7JobsSw755iW83f5jGP5fdjaups0IH+iVPGxdQD2gEH82JME="
jobs:
  include:
   - if: repo = alfasoftware/astra AND head_repo = alfasoftware/astra AND type = pull_request
     name: "Test"
     script:
        - git fetch --quiet
        - mvn clean verify sonar:sonar -Pcoverage -B -U -Dsonar.pullrequest.key=$TRAVIS_PULL_REQUEST -Dsonar.pullrequest.branch=$TRAVIS_PULL_REQUEST_BRANCH -Dsonar.pullrequest.base=$TRAVIS_BRANCH
   - if: repo = alfasoftware/astra AND (branch = main OR tag IS present) AND NOT type = pull_request
     name: "Deploy"
     script:
        - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
        - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
        - mvn clean deploy --settings .maven-settings.xml -B -U -Prelease
