language: java
addons:
  sonarcloud:
    organization: "alfasoftware"
    token:
      secure: "fzGQlxiPAM5XYKWqHnSdxnNKhfEnAvq132D60qU5GrORM3nl15Kwj3ZkIcIZV1ksiwqeQyPJgg/vuPbCB9pRM8w8asDxe8lA9vuEyJpchvG/9+icjI8AfbAfWbOnBDl2d/STll00YUntFkoztLUliauzs5ia1AgPAXiBBd878HXM2G94eAFPIOVI+HfXLv0f08PNoZIfGMrXFAjL+IOh97K6M1114nFDqgCU0MQW3uP1XsEecd2E1XHBWRN1I2Uk27nno/WS3VmcLArOAsmO/9LqsWsn4hNWcoHGYBMX8LQaUoFl8SXXKljvMWAebaUZfkE/7T/nGSp/izpWrjuYj9s9ZExOTAv7+CpzvDQ2yZU/TJsKgGt/eK8cGGXqOLvrM3GhvvrimEmmDnpwaoZH5jg/tfV8Wn60R4oVw1zn7Z1/MKqp9JTvRl7OUBNOGJhbRpD6/vzF2vx6oB3D4hi0q3SqQiCf6MDlfDPOEBPGmAzzG+ez9T3VEokkTrjvFQe2HV4LbQjy8FPP7L8RUtD8LZ97Dm2yo2bmadfB90qSW34w/S11fkM3byZkiQYig15vlXpoVCfMTAg0AFbpSyP3l6RE93qexeCHv4j4GXWed58SeEaTTuuRcX8niYFvOcRp+dEjNmPnLGmMSLiP5+eQjoM1g0hFJ5BM5e6RSTchsi8="
jobs:
  include:
   - if: repo = alfasoftware/astra AND head_repo = alfasoftware/astra AND type = pull_request
     name: "Test"
     script:
        - git fetch --quiet
        - mvn clean test -B -U -Pdefault
   - if: repo = alfasoftware/astra AND (branch = main OR tag IS present) AND NOT type = pull_request
     name: "Deploy"
     script:
        - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
        - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
        - mvn clean deploy --settings .maven-settings.xml -B -U -Prelease
